#ifndef PERSISTENT_EXCEPTION_HPP
#define PERSISTENT_EXCEPTION_HPP

#include <inttypes.h>

namespace persistent {
// Exceptions definition
#define PERSIST_EXP(errcode, usercode) \
    ((((errcode)&0xffffffffull) << 32) | ((usercode)&0xffffffffull))
#define PERSIST_EXP_USERCODE(x) ((uint32_t)((x)&0xffffffffull))
#define PERSIST_EXP_UNIMPLEMENTED PERSIST_EXP(0, 0)
#define PERSIST_EXP_NEW_FAILED_UNKNOWN PERSIST_EXP(1, 0)
#define PERSIST_EXP_STORAGE_TYPE_UNKNOWN(x) PERSIST_EXP(2, (x))
// file system implementation
#define PERSIST_EXP_OPEN_FILE(x) PERSIST_EXP(0x1003, (x))
#define PERSIST_EXP_MMAP_FILE(x) PERSIST_EXP(0x1004, (x))
#define PERSIST_EXP_INV_PATH PERSIST_EXP(0x1005, 0)
#define PERSIST_EXP_CREATE_PATH(x) PERSIST_EXP(0x1006, (x))
#define PERSIST_EXP_INV_FILE PERSIST_EXP(0x1007, 0)
#define PERSIST_EXP_CREATE_FILE(x) PERSIST_EXP(0x1008, (x))
#define PERSIST_EXP_TRUNCATE_FILE(x) PERSIST_EXP(0x1009, (x))
#define PERSIST_EXP_RWLOCK_INIT(x) PERSIST_EXP(0x1010, (x))
#define PERSIST_EXP_RWLOCK_RDLOCK(x) PERSIST_EXP(0x1011, (x))
#define PERSIST_EXP_RWLOCK_WRLOCK(x) PERSIST_EXP(0x1012, (x))
#define PERSIST_EXP_RWLOCK_UNLOCK(x) PERSIST_EXP(0x1013, (x))
#define PERSIST_EXP_MSYNC(x) PERSIST_EXP(0x1014, (x))
#define PERSIST_EXP_INV_ENTRY_IDX(x) PERSIST_EXP(0x1015, (x))
#define PERSIST_EXP_EMPTY_LOG PERSIST_EXP(0x1016, 0)
#define PERSIST_EXP_SPIN_INIT(x) PERSIST_EXP(0x1017, (x))
#define PERSIST_EXP_SPIN_LOCK(x) PERSIST_EXP(0x1018, (x))
#define PERSIST_EXP_SPIN_UNLOCK(x) PERSIST_EXP(0x1019, (x))
#define PERSIST_EXP_INV_VERSION PERSIST_EXP(0x1020, 0)
#define PERSIST_EXP_ALLOC(x) PERSIST_EXP(0x1021, (x))
#define PERSIST_EXP_READ_FUTURE PERSIST_EXP(0x1022, 0)
#define PERSIST_EXP_INV_HLC PERSIST_EXP(0x1023, 0)
#define PERSIST_EXP_MUTEX_INIT(x) PERSIST_EXP(0x1024, (x))
#define PERSIST_EXP_MUTEX_LOCK(x) PERSIST_EXP(0x1025, (x))
#define PERSIST_EXP_MUTEX_UNLOCK(x) PERSIST_EXP(0x1026, (x))
#define PERSIST_EXP_READ_FILE(x) PERSIST_EXP(0x1027, (x))
#define PERSIST_EXP_WRITE_FILE(x) PERSIST_EXP(0x1028, (x))
#define PERSIST_EXP_RENAME_FILE(x) PERSIST_EXP(0x1029, (x))
#define PERSIST_EXP_NOSPACE(x) PERSIST_EXP(0x1030, (x))
#define PERSIST_EXP_NOSPACE_LOG PERSIST_EXP_NOSPACE(1)
#define PERSIST_EXP_NOSPACE_DATA PERSIST_EXP_NOSPACE(2)
#define PERSIST_EXP_BEYOND_GSF PERSIST_EXP(0x1031, 0)
#define PERSIST_EXP_OOM(x) PERSIST_EXP(0x1032, (x))
#define PERSIST_EXP_INV_OBJNAME PERSIST_EXP(0x1033, 0)
#define PERSIST_EXP_REMOVE_FILE(x) PERSIST_EXP(0x1034, (x))
}

#endif  //PERSISTENT_EXCEPTION_HPP
