/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_derecho_Group */

#ifndef _Included_io_derecho_Group
#define _Included_io_derecho_Group
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_derecho_Group
 * Method:    createGroup
 * Signature: (Ljava/util/List;Lio/derecho/IShardViewGenerator;Lio/derecho/Group/ICallbackSet;)J
 */
JNIEXPORT jlong JNICALL Java_io_derecho_Group_createGroup
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     io_derecho_Group
 * Method:    barrierSync
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_derecho_Group_barrierSync
  (JNIEnv *, jobject);

/*
 * Class:     io_derecho_Group
 * Method:    leave
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_io_derecho_Group_leave
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     io_derecho_Group
 * Method:    get_my_rank
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_io_derecho_Group_get_1my_1rank
  (JNIEnv *, jobject);

/*
 * Class:     io_derecho_Group
 * Method:    getMembers
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_io_derecho_Group_getMembers
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
