/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_derecho_Replicated */

#ifndef _Included_io_derecho_Replicated
#define _Included_io_derecho_Replicated
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_derecho_Replicated
 * Method:    send
 * Signature: (JLio/derecho/IMessageGenerator;)V
 */
JNIEXPORT void JNICALL Java_io_derecho_Replicated_send
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     io_derecho_Replicated
 * Method:    ordered_send
 * Signature: (Ljava/lang/String;[B[B)J
 */
JNIEXPORT jlong JNICALL Java_io_derecho_Replicated_ordered_1send
  (JNIEnv *, jobject, jstring, jbyteArray, jbyteArray);

/*
 * Class:     io_derecho_Replicated
 * Method:    p2p_send
 * Signature: (IILjava/lang/String;[B[B)J
 */
JNIEXPORT jlong JNICALL Java_io_derecho_Replicated_p2p_1send
  (JNIEnv *, jobject, jint, jint, jstring, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
