/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ObjectStoreService */

#ifndef _Included_ObjectStoreService
#define _Included_ObjectStoreService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ObjectStoreService
 * Method:    initialize
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ObjectStoreService_initialize
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ObjectStoreService
 * Method:    putNative
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ObjectStoreService_put
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     ObjectStoreService
 * Method:    removeNative
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_ObjectStoreService_remove
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ObjectStoreService
 * Method:    getNative
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ObjectStoreService_get
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ObjectStoreService
 * Method:    leave
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ObjectStoreService_leave
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
