name: Build Check
run-name: ${{ github.actor }} is running build check.
on:  [push]
jobs:
  Placeholder:
    runs-on: ubuntu-latest
    steps:
      - run:  echo "The job is automatically triggered by a ${{ github.event_name }} event."
      - run:  sudo apt update; sudo apt install libssl-dev librdmacm-dev libibverbs-dev libspdlog-dev -y
      - run:  g++ --version
      - run:  cmake --version 
      - run:  lscpu
      - run:  df -ha
      - run:  cat /proc/meminfo
      - name: Checkout repository code
        uses: actions/checkout@v3
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Install libfabric
        run:  derecho/scripts/prerequisite/install-libfabric.sh $HOME/opt
      - name: Install json library
        run:  derecho/scripts/prerequisite/install-json.sh $HOME/opt
      - name: Install mutils
        run:  derecho/scripts/prerequisite/install-mutils.sh $HOME/opt
      - name: Install mutils-containers
        run:  derecho/scripts/prerequisite/install-mutils-containers.sh $HOME/opt
      - run:  export PREFIX=$HOME/opt
      - run:  export CMAKE_PREFIX_PATH=$PREFIX
      - run:  export C_INCLUDE_PATH=$PREFIX/include/
      - run:  export CPLUS_INCLUDE_PATH=$PREFIX/include/
      - run:  export LIBRARY_PATH=$PREFIX/lib/:$PREFIX/lib64/
      - run:  export LD_LIBRARY_PATH=$PREFIX/lib/:$PREFIX/lib64/
      - run:  cd derecho
      - run:  echo "The job's status is ${{ job.status }}."
