name: Build Check
run-name: ${{ github.actor }} is running build check.
on:  [push]
jobs:
  Placeholder:
    runs-on: ubuntu-latest
    steps:
      - run:  echo "The job is automatically triggered by a ${{ github.event_name }} event."
      - run:  sudo apt update; sudo apt install libssl-dev librdmacm-dev libibverbs-dev libspdlog-dev -y
      - run:  g++ --version
      - run:  cmake --version 
      - run:  lscpu
      - run:  df -ha
      - run:  cat /proc/meminfo
      - name: Checkout repository code
        uses: actions/checkout@v3
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Install libfabric
        run:  ${{ github.workspace }}/scripts/prerequisites/install-libfabric.sh ${{ github.workspace }}/opt
      - name: Install json library
        run:  ${{ github.workspace }}/scripts/prerequisites/install-json.sh ${{ github.workspace }}/opt
      - name: Install mutils
        run:  ${{ github.workspace }}/scripts/prerequisites/install-mutils.sh ${{ github.workspace }}/opt
      - name: Install mutils-containers
        run:  ${{ github.workspace }}/scripts/prerequisites/install-mutils-containers.sh ${{ github.workspace }}/opt
      - run:  cd ${{ github.workspace }}
      - run:  mkdir build-Release
      - name: Build Derecho
        run:  >
              cd build-Release;
              export PREFIX=${{ github.workspace }}/opt;
              export CMAKE_PREFIX_PATH=$PREFIX;
              export C_INCLUDE_PATH=$PREFIX/include/;
              export CPLUS_INCLUDE_PATH=$PREFIX/include/;
              export LIBRARY_PATH=$PREFIX/lib/:$PREFIX/lib64/;
              export LD_LIBRARY_PATH=$PREFIX/lib/:$PREFIX/lib64/;
              cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_INSTALL_PREFIX=${PREFIX} ..;
              make -j2;
              make install
      - run:  echo "The job's status is ${{ job.status }}."
